apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
  labels:
    app: django-clearsessions
spec:
  schedule: "0 0 * * *"
  startingDeadlineSeconds: 60
  ttlSecondsAfterFinished: 30
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: django-clearsessions
            image: sgkond/lesson-kuber-1
            imagePullPolicy: IfNotPresent
            command:
              - python
              - manage.py
              - clearsessions
            envFrom:
              - configMapRef:
                name: django-app-config
          restartPolicy: OnFailure