version: "3"

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      # - 192.168.43.64:5432:5432
     # - 192.168.0.100:5432:5432
      - 192.168.0.102:5432:5432
       # - 192.168.0.2:5432:5432
        #- 192.168.1.36:5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB-test_k8s}
      POSTGRES_USER: ${POSTGRES_USER-test_k8s}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-OwOtBep9Frut}
volumes:
  db_data:


